#!/usr/bin/env python3
"""Copy the program modules from ``src/omni_pca`` into the integration.

Home Assistant installs the ``omni-pca`` library from PyPI, and the
pinned release decodes program records wrongly for a real panel. The
integration therefore carries its own copy of the three program
modules under ``custom_components/omni_pca/bundled/`` and imports them
from there. ``src/omni_pca`` stays the place to edit; run this script
afterwards to refresh the copy.

    python dev/sync_bundled.py           # rewrite the bundled copy
    python dev/sync_bundled.py --check   # exit 1 if it is out of date

Imports of the bundled modules stay relative to each other; every other
relative import is pointed at the installed ``omni_pca`` library.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
_SRC = _ROOT / "src" / "omni_pca"
_DEST = _ROOT / "custom_components" / "omni_pca" / "bundled"

MODULES: tuple[str, ...] = ("programs", "program_engine", "program_renderer")

_HEADER = (
    "# GENERATED by dev/sync_bundled.py from src/omni_pca/{name}.py.\n"
    "# Edit that file and re-run the script; do not edit this copy.\n"
)
_RELATIVE_IMPORT = re.compile(r"^(\s*from )\.(\w+)( import )", re.MULTILINE)

_INIT = '''"""Program modules bundled from ``src/omni_pca``.

Generated by ``dev/sync_bundled.py``; see that script for why the
integration carries its own copy instead of using the installed library.
"""
'''


def _rewrite(match: re.Match[str]) -> str:
    module = match.group(2)
    if module in MODULES:
        return match.group(0)
    return f"{match.group(1)}omni_pca.{module}{match.group(3)}"


def render(name: str) -> str:
    """Return the bundled text for one module."""
    source = (_SRC / f"{name}.py").read_text()
    return _HEADER.format(name=name) + _RELATIVE_IMPORT.sub(_rewrite, source)


def expected_files() -> dict[Path, str]:
    files = {_DEST / "__init__.py": _INIT}
    for name in MODULES:
        files[_DEST / f"{name}.py"] = render(name)
    return files


def stale_files() -> list[Path]:
    """Bundled files that are missing or differ from what we'd write."""
    return [
        path
        for path, text in expected_files().items()
        if not path.exists() or path.read_text() != text
    ]


def main(argv: list[str]) -> int:
    if "--check" in argv:
        stale = stale_files()
        for path in stale:
            print(f"out of date: {path.relative_to(_ROOT)}")
        return 1 if stale else 0
    _DEST.mkdir(exist_ok=True)
    for path, text in expected_files().items():
        path.write_text(text)
        print(f"wrote {path.relative_to(_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
